# """
# #++++++++++++++++++++++++++++++++++++++++++++++

#     Project: Part of final project for Georgia Tech Institute of Technology course DL, CS 7643. 

#     Totality of this code is non-proprietary and may be used at will. 

# #++++++++++++++++++++++++++++++++++++++++++++++


# Description: 

# @brief Defines top level configuration settings for training and evaluation process. 

# @author: Greg Zdor (gzdor@icloud.com)

# @date Date_Of_Creation: 4/16/2023 

# @date Last_Modification 4/16/2023 

# No Copyright - use at will

# """


dataset_parameters:            !include "../src/pkgs/dataset/memory_mapper_tuning.yml"

model_parameters:              !include "../src/pkgs/ml/model_config_tuning.yaml"

lightning_trainer_parameters:  !include "../src/pkgs/ml/pl_trainer_config_tuning.yaml"

# Run via:  python3 model_trainer.py  -cfg ../../../configs/rf_fingerprinting_cfg_tuning.yaml 
