# """
# #++++++++++++++++++++++++++++++++++++++++++++++

#     Project: Part of final project for Georgia Tech Institute of Technology course DL, CS 7643. 

#     Totality of this code is non-proprietary and may be used at will. 

# #++++++++++++++++++++++++++++++++++++++++++++++


# Description: 

# @brief Defines top level configuration settings for training and evaluation process. 

# @author: Greg Zdor (gzdor@icloud.com)

# @date Date_Of_Creation: 4/16/2023 

# @date Last_Modification 4/16/2023 

# No Copyright - use at will

# """


dataset_parameters:            "../src/pkgs/dataset/memory_mapper.yml"

model_parameters:              "../src/pkgs/ml/model_config.yaml"

lightning_trainer_parameters:   "../src/pkgs/ml/pl_trainer_config.yaml"
